<#
.SYNOPSIS
    SOTA Fleet Heartbeat - Modified File Tracker for the Antigravity Fleet.
    Uses WizTree for high-speed MFT analysis and PowerShell for surgical filtering.

.PARAMETER LookbackHours
    Number of hours to look back for modifications. Default is 4.

.PARAMETER ScanPaths
    Comma-separated list of paths to scan. Default is "D:\Dev\repos".

.PARAMETER OutputFile
    Path to save the Markdown report. Default is "D:\Dev\repos\fleet-heartbeat-report.md".
#>

Param(
    [int]$LookbackHours = 4,
    [string[]]$ScanPaths = @("D:\Dev\repos"),
    [string]$OutputFile = "D:\Dev\repos\fleet-heartbeat-report.md"
)

$WizTreePath = "C:\Program Files\WizTree\WizTree64.exe"
$TempCsv = Join-Path $env:TEMP "fleet_heartbeat_$(Get-Random).csv"
$LookbackDate = (Get-Date).AddHours(-$LookbackHours)

Write-Host "[Heartbeat] Initiating MFT Scan of $($ScanPaths -join ', ')..." -ForegroundColor Cyan
Write-Host "[Heartbeat] Lookback: $LookbackDate" -ForegroundColor Gray

# Create Scan String for WizTree (it only takes one path at a time in some versions, but we'll loop)
$Results = New-Object System.Collections.Generic.List[PSObject]

foreach ($Path in $ScanPaths) {
    if (-not (Test-Path $Path)) {
        Write-Warning "Path not found: $Path"
        continue
    }

    $Proc = Start-Process -FilePath $WizTreePath -ArgumentList "`"$Path`"", "/export=`"$TempCsv`"", "/quit", "/admin=1" -Wait -PassThru -WindowStyle Hidden
    
    if (Test-Path $TempCsv) {
        # WizTree CSV has a commentary line at index 0. Import-Csv needs skipping it.
        $CsvContent = Get-Content $TempCsv | Select-Object -Skip 1 | ConvertFrom-Csv
        
        foreach ($item in $CsvContent) {
            $modDate = [DateTime]::Parse($item.Modified)
            if ($modDate -ge $LookbackDate) {
                $Results.Add([PSCustomObject]@{
                    Path = $item.'File Name'
                    Size = $item.Size
                    Modified = $modDate
                })
            }
        }
        Remove-Item $TempCsv -Force
    }
}

# Sort by most recent
$SortedResults = $Results | Sort-Object Modified -Descending

# Generate Markdown Report
$Report = @"
# 💓 Fleet Heartbeat Report
**Generated:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
**Lookback Window:** $LookbackHours hours (since $LookbackDate)

## 🕒 Recently Modified Files
$(if ($SortedResults.Count -eq 0) { "No modifications found in the lookback window." } else {
    $SortedResults | ForEach-Object {
        $sizeMB = [math]::Round($_.Size / 1MB, 2)
        "- [$($_.Modified.ToString('HH:mm'))] ``$($_.Path)`` ($sizeMB MB)"
    } | Out-String
})

---
*Generated by Antigravity Fleet Heartbeat SOTA 2026*
"@

$Report | Out-File -FilePath $OutputFile -Encoding utf8
Write-Host "[Heartbeat] Report generated at: $OutputFile" -ForegroundColor Green
